<a href="https://colab.research.google.com/github/briskicedteaa/CFTR-Variant-Explorer/blob/main/notebooks/CFTR_Variant_Exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install biopython
from Bio import SeqIO

Collecting biopython
  Downloading biopython-1.88-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from biopython) (2.1.3)
Downloading biopython-1.88-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 10.3 MB/s eta 0:00:00
Installing collected packages: biopython
Successfully installed biopython-1.88

In [ ]:
import pandas as pd

df = pd.read_json("P13569.json")

count = df["features"].apply(lambda x: "begin" in x).sum()
count2 = df["features"].apply(lambda x: "wildType" in x).sum()
count3 = df["features"].apply(lambda x: "mutatedType" in x).sum()
count4 = df["features"].apply(lambda x: "consequenceType" in x).sum()
count5 = df["features"].apply(lambda x: "clinicalSignificances" in x).sum()
count6 = df["features"].apply(lambda x: "association" in x).sum()
print("Begin:", count,"wildType:", count2,"mutatedType:", count3,"consequenceType:", count4,"clinicalSignificances:", count5,"association:", count6)

Begin: 3664 wildType: 3664 mutatedType: 3216 consequenceType: 3664 clinicalSignificances: 2909 association: 2895

In [ ]:
variants = []

for feature in df["features"]:
  variants.append({
      "Position": int(feature["begin"]),
      "WildType": feature["wildType"],
      "MutatedType": feature.get("mutatedType"),
      "Consequence": feature["consequenceType"]
  })

variants_df = pd.DataFrame(variants)
variants_df["Position"].describe()
variants_df["Position"].nunique()
variants_df.head()

   Position WildType MutatedType              Consequence
0         1        M        None  initiator codon variant
1         1        M           I                 missense
2         1        M           K                 missense
3         1        M           R                 missense
4         1        M           T                 missense

In [ ]:
variants_df["Position"].value_counts().head(20)

Position
1098    8
508     8
137     8
311     7
14      7
17      7
1295    7
1023    7
1130    6
161     6
1       6
224     6
1054    6
60      6
1285    6
506     6
111     6
258     6
317     6
1282    6
Name: count, dtype: int64

In [54]:
variants_df["Consequence"].value_counts()

Consequence
missense                   2809
frameshift                  459
stop gained                 316
inframe deletion             52
-                            13
insertion                    11
stop lost                     3
initiator codon variant       1
Name: count, dtype: int64